### ISSUE TITLE
Config question

### ISSUE THREAD

**Issue by rmlopes** [burkemw3/docker-nginx-proxy-path#1]
Thanks @burkemw3 , I was looking for this exactly!

I think I am configuring something wrong though. Can you see what I am doing wrong? (I can access the app at `0.0.0.0:3000`)

### Log

```
nginx-proxy_1  | nginx.1    | 2019/05/30 15:38:03 [error] 35#35: *1 open() "/usr/share/nginx/html/mypath" failed (2: No such file or directory), client: 172.24.0.1, server: localhost, request: "GET /mypath HTTP/1.1", host: "localhost"
nginx-proxy_1  | nginx.1    | 172.24.0.1 - - [30/May/2019:15:38:03 +0000] "GET /mypath HTTP/1.1" 404 571 "-" "Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/73.0.3683.75 Safari/537.36" "-"
nginx-proxy_1  | 2019/05/30 15:38:17 [emerg] 48#48: no host in upstream ":3000" in /etc/nginx/conf.d/default.conf:3
nginx-proxy_1  | nginx: [emerg] no host in upstream ":3000" in /etc/nginx/conf.d/default.conf:3
```

### Nginx compose
```
#built from github with nginx-proxy-path tag
version: "3.5"
services:
  nginx-proxy:
    image: nginx-proxy-path
    ports:
      - 80:80
    volumes:
      - /var/run/docker.sock:/tmp/docker.sock:ro
    networks:
      - proxy

networks:
  proxy:
```

### App compose
```
version: "3"

services:
  data-api:
    build: ./api
    environment:
      VIRTUAL_PATH: mypath
    expose: 
      - 3000
    ports:
      - "3000:3000"

networks:
  default:
    external:
      name: nginx_proxy
```
